name: quadtree_dart
description: A lightweight, extensive implementation of Quadtrees in Dart.
version: 1.1.0
homepage: https://rjmath-quadtree.web.app
repository: https://github.com/rlch/quadtree-dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  quiver: ^3.0.1

dev_dependencies:
  lint: ^1.5.2
